---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: aidio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aidio 
  name: aidio
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi