apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: aidio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aidio 
  name: aidio
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: aidio 
    weight: 100 
  wildcardPolicy: None
